# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # All commits, so we can look at the tags
          ref: main
          path: main
      - name: Checkout Pages
        uses: actions/checkout@v2
        with:
          ref: pages
          path: pages
      - name: Generate Pages
        run: |
          cd main
          yarn
          yarn run build
          yarn run release
          cp -rf release/* $GITHUB_WORKSPACE/pages/
      - name: Commit & Push
        run: |
          cd pages
          git config --global user.name 'deploy'
          git config --global user.email 'deploy@users.noreply.github.com'
          git add .
          git commit -m "Updated"
          git push --force
